### ISSUE TITLE
Package.json exports field somehow confuses Rollup

### ISSUE THREAD

**Issue by jgonggrijp** [CentreForDigitalHumanities/js-timing-util#3]
While bundling a project that indirectly uses `@uu-cdh/timing-util` through[ `@uu-cdh/backbone-util`](https://github.com/CentreForDigitalHumanities/backbone-util), Rollup issues the following warnings:

```
Could not resolve import "@uu-cdh/timing-util/fastTimeout.js" in node_modules/@uu-cdh/backbone-util/src/future-attribute.js using exports defined in node_modules/@uu-cdh/timing-util/package.json.
'@uu-cdh/timing-util/fastTimeout.js' is imported by node_modules/@uu-cdh/backbone-util/src/future-attribute.js, but could not be resolved – treating it as an external dependency
```

`exports defined in node_modules/@uu-cdh/timing-util/package.json` refers to this, but I don't see a problem with it:

https://github.com/CentreForDigitalHumanities/js-timing-util/blob/0e644eb4c63529822974a46b0328a73e9f20c008/package.json#L17-L22

I double-checked the contents of the `node_modules` and all the files are there.

**Comment by ar-jan** [comment]
What's the easiest way to reproduce this? (I haven't used either of these packages).

**Comment by jgonggrijp** [comment]
Make a local clone of EDPOP and run `docker compose up frontend`.
